classification_tag: v
dataloader_args:
  batch_size: 32
  num_workers: 1
dataset_args:
  classification_tag: v
  data_dir: /work3/luivog/Nexus/preprocessed_data
  data_tag: nexus
  sample_size: 1
  split:
  - 0.8
  - 0.1
  - 0.1
device: cuda
evaluation: runs/SelectedCrossTransformer/nexus/valence/all/no_grouping/143200
model_args:
  channel_grouping: null
  classification_tag: v
  data_dim: 8
  dropout: 0.1
  e_layers: 3
  factor: 4
  ff_dim: 512
  hidden_dim: 128
  in_length: 250
  log: false
  lr: 0.0001
  lr_decay: null
  momentum: 0.9
  num_heads: 4
  seg_length: 5
  tag: SelectedCrossTransformer/nexus/valence/all/no_grouping
  weight_decay: 0
  win_size: 1
model_name: SelectedCrossTransformer
save_every: 100
seed: None
train_epochs: 20
