classification_tag: a
dataloader_args:
  batch_size: 32
  num_workers: 0
dataset_args:
  classification_tag: a
  data_dir: /work3/luivog/SEED_EEG/subj_4best
  data_tag: seed
  sample_size: 1
  split:
  - 0.8
  - 0.1
  - 0.1
device: cuda
evaluation: runs/SelectedCrossTransformer/seed/best4/no_grouping/172025
model_args:
  channel_grouping: null
  classification_tag: a
  data_dim: 62
  dropout: 0.1
  e_layers: 3
  factor: 4
  ff_dim: 512
  hidden_dim: 128
  in_length: 200
  log: false
  lr: 0.001
  lr_decay: 0.5
  momentum: 0.9
  num_heads: 4
  seg_length: 5
  tag: SelectedCrossTransformer/seed/best4/no_grouping
  weight_decay: 0.01
  win_size: 1
model_name: SelectedCrossTransformer
save_every: 100
seed: None
train_epochs: 20
