classification_tag: a
dataloader_args:
  batch_size: 32
  num_workers: 1
dataset_args:
  classification_tag: a
  data_dir: /work3/luivog/SEED_EEG/subj6
  data_tag: seed
  sample_size: 1
  split:
  - 0.6
  - 0.2
  - 0.2
device: cuda
evaluation: runs/SelectedCrossTransformer/seedsubjs/subj6/112707
model_args:
  channel_grouping:
    0:
    - 0
    - 3
    - 5
    - 6
    - 7
    - 8
    - 14
    - 15
    - 16
    - 17
    1:
    - 2
    - 4
    - 10
    - 11
    - 12
    - 13
    - 19
    - 20
    - 21
    - 22
    2:
    - 32
    - 33
    - 34
    - 35
    - 41
    - 42
    - 43
    - 44
    - 50
    - 51
    - 52
    - 57
    - 58
    3:
    - 37
    - 38
    - 39
    - 40
    - 46
    - 47
    - 48
    - 49
    - 54
    - 55
    - 56
    - 60
    - 61
    4:
    - 1
    - 9
    - 18
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 36
    - 45
    - 53
    - 59
  classification_tag: a
  data_dim: 62
  dropout: 0.1
  e_layers: 3
  factor: 4
  ff_dim: 512
  hidden_dim: 128
  in_length: 200
  log: false
  lr: 0.01
  lr_decay: 0.5
  momentum: 0.9
  num_heads: 4
  seg_length: 5
  tag: SelectedCrossTransformer/seedsubjs/subj6
  weight_decay: 0
  win_size: 1
model_name: SelectedCrossTransformer
save_every: 10
seed: None
train_epochs: 15
