device: cuda
seed: None
evaluation: None
train_epochs: 10
classification_tag: a
dataset_args:
    split: [0.6, 0.2, 0.2]
    data_dir: /home/s210382/Insai/DTU/Data/SEED_EEG/Preprocessed_EEG_Single_Full
    data_tag: seed
    sample_size: 1
dataloader_args:
    batch_size: 32
    num_workers: 0
model_name: SelectedCrossTransformer
save_every: 10
model_args:
    tag: SelectedCrossTransformer/multiple_subjects
    log: True
    data_dim: 62
    channel_grouping: seed
    seg_length: 5
    win_size: 1
    factor: 4
    hidden_dim: 128
    ff_dim: 512
    num_heads: 4
    e_layers: 4
    lr: 0.01
    lr_decay: 0.5
    momentum: 0.9
    weight_decay: 0.01
    dropout: 0.1