device: cpu
seed: None
evaluation: None
train_epochs: 5
classification_tag: a
dataset_args:
    split: [0.6, 0.2, 0.2]
    data_dir: /Users/luisevogt/Uni/Master/Thesis/Emotion-Recognition-With-A-Pre-Trained-Multimodal-Transformer-Using-Eeg-Signals/datasets/DREAMER/subj_files_std
    data_tag: dreamer
dataloader_args:
    batch_size: 4
    num_workers: 1
model_name: SelectedCrossTransformer
save_every: 10
model_args:
    tag: SelectedCrossTransformer/test_2
    log: True
    data_dim: 14
    channel_grouping: dreamer
    win_size: 1
    hidden_dim: 128
    ff_dim: 512
    num_heads: 4
    e_layers: 3
    lr_decay: 0.5
    momentum: 0.9
    weight_decay: 0.01
    dropout: 0.1