device: cpu
seed: None
evaluation: None
train_epochs: 10
classification_tag: a
dataset_args:
    split: [0.8, 0.1, 0.1]
    data_dir: datasets/DEAP/data_normalized_python
    data_tag: deap
    sample_size: 6
dataloader_args:
    batch_size: 4
    num_workers: 1
model_name: SelectedCrossTransformer
save_every: 10
model_args:
    tag: SelectedCrossTransformer/test_1
    log: True
    data_dim: 32
    channel_grouping: deap
    seg_length: 96
    win_size: 1
    factor: 10
    hidden_dim: 128
    ff_dim: 256
    num_heads: 4
    e_layers: 3
    lr: 0.1
    lr_decay: 0.5
    momentum: 0.9
    weight_decay: 0.01
    dropout: 0.1