classification_tag: d
dataloader_args:
  batch_size: 32
  num_workers: 1
dataset_args:
  classification_tag: d
  data_dir: /work3/luivog/DREAMER/top12
  data_tag: dreamer
  sample_size: 1
  split:
  - 0.8
  - 0.1
  - 0.1
device: cuda
evaluation: runs/SelectedCrossTransformer/dreamer/dominance/all/no_grouping_top12/004253
model_args:
  channel_grouping: null
  classification_tag: d
  data_dim: 14
  dropout: 0.1
  e_layers: 3
  factor: 4
  ff_dim: 512
  hidden_dim: 128
  in_length: 128
  log: false
  lr: 0.01
  lr_decay: 0.5
  momentum: 0.9
  num_heads: 4
  seg_length: 4
  tag: SelectedCrossTransformer/dreamer/dominance/all/no_grouping_top12
  weight_decay: 0
  win_size: 1
model_name: SelectedCrossTransformer
save_every: 100
seed: None
train_epochs: 15
