name: thesis
channels:
  - pytorch
  - conda-forge
dependencies:
  - aiohttp=3.8.3
  - aiosignal=1.3.1
  - anyio=3.6.2
  - aom=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - async-timeout=4.0.2
  - attrs=22.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.2
  - bleach=6.0.0
  - blosc=1.21.3
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.6.1
  - ca-certificates=2022.12.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.4.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - colorspacious=1.1.2
  - comm=0.1.2
  - contourpy=1.0.7
  - cryptography=39.0.0
  - curl=7.87.0
  - cycler=0.11.0
  - cytoolz=0.12.0
  - darkdetect=0.8.0
  - dask-core=2023.1.1
  - dav1d=1.0.0
  - debugpy=1.6.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - dipy=1.5.0
  - double-conversion=3.2.0
  - edflib-python=1.0.6
  - eeglabio=0.0.2.post3
  - eigen=3.4.0
  - einops=0.4.1
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - ffmpeg=5.1.2
  - filelock=3.11.0
  - flit-core=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.38.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - fsspec=2023.1.0
  - future=0.18.3
  - gettext=0.21.1
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.74.1
  - glib-tools=2.74.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - h5io=0.1.7
  - h5py=3.8.0
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - ignite=0.4.11
  - imagecodecs=2023.1.23
  - imageio=2.25.0
  - imageio-ffmpeg=0.4.8
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.10.2
  - ipycanvas=0.13.1
  - ipyevents=2.0.1
  - ipykernel=6.21.1
  - ipython=8.9.0
  - ipython_genutils=0.2.0
  - ipyvtklink=0.2.3
  - ipywidgets=7.7.2
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsoncpp=1.9.5
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.0.2
  - jupyter_console=6.4.4
  - jupyter_core=5.2.0
  - jupyter_events=0.6.3
  - jupyter_server=2.2.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.1
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.1.4
  - liblapack=3.9.0
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libmatio=1.5.23
  - libnetcdf=4.8.1
  - libnghttp2=1.51.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.1
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzip=1.9.2
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=15.0.7
  - llvmlite=0.39.1
  - locket=1.0.0
  - loguru=0.6.0
  - lxml=4.9.2
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.6.3
  - matplotlib-base=3.6.3
  - matplotlib-inline=0.1.6
  - mffpy=0.8.0
  - mistune=2.0.4
  - mne=1.3.0
  - mne-base=1.3.0
  - mne-qt-browser=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - multidict=6.0.4
  - munkres=1.1.4
  - mysql-common=8.0.31
  - mysql-libs=8.0.31
  - nbclassic=0.5.1
  - nbclient=0.7.2
  - nbconvert=7.2.9
  - nbconvert-core=7.2.9
  - nbconvert-pandoc=7.2.9
  - nbformat=5.7.3
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=3.0
  - nibabel=5.0.0
  - nilearn=0.10.0
  - nlohmann_json=3.11.2
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.78
  - numba=0.56.4
  - numexpr=2.8.3
  - numpy=1.23.5
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openmeeg=2.5.5
  - openssl=3.1.0
  - p11-kit=0.24.1
  - packaging=23.0
  - pandas=1.5.3
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.6.2
  - ply=3.11
  - pooch=1.6.0
  - proj=9.1.1
  - prometheus_client=0.16.0
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.4
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pugixml=1.11.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.14.0
  - pymatreader=0.0.30
  - pyobjc-core=9.0
  - pyobjc-framework-cocoa=9.0
  - pyopengl=3.1.6
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtgraph=0.13.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pytables=3.7.0
  - python=3.10.9
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.4
  - python-picard=0.7
  - python_abi=3.10
  - pytorch=2.0.0
  - pytz=2022.7.1
  - pyvista=0.38.1
  - pyvistaqt=0.9.0
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.0.0
  - qdarkstyle=3.1
  - qt-main=5.15.6
  - qtpy=2.3.0
  - readline=8.1.2
  - requests=2.28.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-image=0.19.3
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - scooby=0.7.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.0
  - setuptools=67.1.0
  - sip=6.7.6
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.0
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - svt-av1=1.4.1
  - sympy=1.11.1
  - tbb=2021.7.0
  - tbb-devel=2021.7.0
  - terminado=0.17.1
  - threadpoolctl=3.1.0
  - tifffile=2023.1.23.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - tornado=6.2
  - tqdm=4.64.1
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - unicodedata2=15.0.0
  - urllib3=1.26.14
  - utfcpp=3.2.3
  - vtk=9.2.5
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.0
  - wheel=0.38.4
  - widgetsnbextension=3.6.1
  - wrapt=1.14.1
  - wslink=1.10.0
  - x264=1!164.3095
  - x265=3.5
  - xlrd=2.0.1
  - xmltodict=0.13.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.8.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.12.0
  - zlib=1.2.13
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
      - absl-py==1.4.0
      - cachetools==5.3.0
      - cython==0.29.33
      - google-auth==2.17.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.54.0
      - markdown==3.4.3
      - oauthlib==3.2.2
      - protobuf==4.22.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - screeninfo==0.8.1
      - tensorboard==2.12.2
      - tensorboard-data-server==0.7.0
      - tensorboard-plugin-wit==1.8.1
      - werkzeug==2.3.0
